runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6

handlers:
- url: /assets/css
  static_dir: assets/css
- url: /assets/img
  static_dir: assets/img
- url: /.*
  script: blog.application
